services:
  - type: web
    name: phrase-lexicon
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GOOGLE_DOC_TAB
        value: t.x0jh4b5vn4op
      - key: BUILD_ID
        value: 3bb89ef-4
